### PR TITLE
DASB refactor- hyperparam tunining

### PR DESCRIPTION
**Pull request by poonehmousavi**
- ADD BOBH hyper-param tuning for DASB

### CODE REVIEW

**Comment by lucadellalib** [comment]
Is this PR still relevant?

**Comment by poonehmousavi** [comment]
> Is this PR still relevant?

his PR, which relates to the tokenizer interface and other refactoring work, has already been merged with 

[ this PR](https://github.com/speechbrain/benchmarks/pull/47 ) for code extraction. Therefore, it doesn’t require additional review.

**Comment by poonehmousavi** [comment]
The hyperparameter tuning is addressed in [this PR](https://github.com/speechbrain/benchmarks/pull/47), so I close this one.

**Comment by poonehmousavi** [comment]
The hyperparameter tuning is addressed in [this PR](https://github.com/speechbrain/benchmarks/pull/47), so I close this one.

**Pull request closed without merging**
